name: SwapnapurtiBuild
on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4.1.0

      - name: Run lint
        run: ./gradlew lintDebug
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: upload lint html test report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4.1.0

      - name: run tests
        run: ./gradlew test
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: upload test report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  build:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup java sdk
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with gradle
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SwapnapurtiApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
